"""
TraceML run comparison helpers.

This package compares two structured final summary JSON artifacts generated by
TraceML and produces both a machine-readable comparison JSON and a compact
human-readable text summary.
"""

from traceml.compare.command import compare_summaries

__all__ = ["compare_summaries"]
