# Copyright 2026 OptAI UG (haftungsbeschraenkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0

"""Top-level HTML document assembly for the run report."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from traceml_ai import __version__

from .banner import render_banner
from .sections import render_sections
from .style import STYLESHEET
from .textutils import esc

# Header chips, in display order: (payload meta key, label).
_META_CHIPS = (
    ("mode", "mode"),
    ("world_size", "world size"),
    ("nodes_observed", "nodes"),
    ("gpus_observed", "GPUs"),
)


def _chips(payload: Dict[str, Any]) -> str:
    meta = payload.get("meta") or {}
    parts: List[str] = []
    for key, label in _META_CHIPS:
        value = meta.get(key)
        if value is None:
            continue
        parts.append(
            f'<span class="chip">{esc(label)} <b>{esc(value)}</b></span>'
        )
    duration = payload.get("duration_s")
    if isinstance(duration, (int, float)):
        parts.append(
            f'<span class="chip">duration <b>{duration:,.1f}&thinsp;s</b>'
            "</span>"
        )
    generated = payload.get("generated_at")
    if generated:
        parts.append(
            f'<span class="chip">generated <b>{esc(generated)}</b></span>'
        )
    return "".join(parts)


def _raw_json(payload: Dict[str, Any]) -> str:
    """Pretty-printed payload, escaped inside a <pre> (no script embedding)."""
    try:
        text = json.dumps(payload, indent=1, sort_keys=False)
    except (TypeError, ValueError):
        text = "(payload is not JSON-serializable)"
    return (
        "<details><summary>Raw final_summary.json</summary>"
        f'<pre class="raw">{esc(text)}</pre></details>'
    )


def _footer(payload: Dict[str, Any], source_label: Optional[str]) -> str:
    schema = payload.get("schema_version", "—")
    text = (
        f"Generated by TraceML v{esc(__version__)} &middot; "
        f"schema {esc(schema)}"
    )
    if source_label:
        text += f" &middot; {esc(source_label)}"
    return f"<footer>{text}</footer>"


def render_html_report(
    payload: Dict[str, Any],
    *,
    source_label: Optional[str] = None,
) -> str:
    """
    Render a final-summary payload to a self-contained HTML document.

    Pure function of (payload, source_label, installed traceml_ai version):
    no I/O, no clock, no randomness. Every payload-derived string is escaped.
    """
    meta = payload.get("meta") or {}
    run_name = meta.get("run_name")
    title = esc(run_name) if run_name else "run report"
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en"><head><meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, '
        'initial-scale=1">\n'
        f"<title>TraceML report &mdash; {title}</title>\n"
        f"<style>{STYLESHEET}</style></head><body>\n"
        '<div class="wrap">\n'
        '<header class="run"><div class="logo">Trace<span>ML</span> '
        f"run report</div><h1>{title}</h1></header>\n"
        f'<div class="meta-chips">{_chips(payload)}</div>\n'
        f"{render_banner(payload)}\n"
        f"{render_sections(payload)}\n"
        f"{_raw_json(payload)}\n"
        f"{_footer(payload, source_label)}\n"
        "</div></body></html>"
    )


__all__ = ["render_html_report"]
