# Copyright 2026 OptAI UG (haftungsbeschraenkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0

"""Run manifest and static code-manifest helpers for the TraceML launcher."""

from __future__ import annotations

import json
import socket
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from traceml_ai.utils.ast_analysis import analyze_script, build_code_manifest
from traceml_ai.utils.atomic_io import write_json_atomic

FINALIZATION_ERROR_NAME = "finalization_error.json"
FINALIZATION_WARNING_NAME = "finalization_warning.json"


def utc_now_iso() -> str:
    """Return the current UTC timestamp as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def node_artifact_dir(session_root: Path, node_rank: int) -> Path:
    """Return the collision-free artifact directory owned by one node."""
    return Path(session_root).resolve() / "nodes" / f"node_{int(node_rank)}"


def load_json_or_warn(path: Path) -> Dict[str, Any]:
    """Load JSON from disk, returning an empty dict for missing/bad files."""
    path = Path(path).resolve()

    if not path.exists():
        return {}

    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        corrupt_path = path.with_suffix(path.suffix + ".corrupt")
        try:
            corrupt_path.write_text(
                path.read_text(encoding="utf-8"), encoding="utf-8"
            )
        except Exception:
            pass
        print(
            f"[TraceML] WARNING: manifest is malformed and will be rebuilt: {path} ({exc})",
            file=sys.stderr,
        )
        return {}
    except OSError as exc:
        print(
            f"[TraceML] WARNING: manifest could not be read and will be rebuilt: {path} ({exc})",
            file=sys.stderr,
        )
        return {}


def _is_current_json_artifact(
    path: Path,
    *,
    aggregator_started_at: str,
    timestamp_field: str,
) -> bool:
    """Return whether a timestamped JSON artifact belongs to this aggregator."""
    path = Path(path).resolve()
    if not path.is_file():
        return False

    try:
        with open(path, "r", encoding="utf-8") as f:
            payload = json.load(f)
    except json.JSONDecodeError:
        return False
    except OSError as exc:
        print(
            f"[TraceML] WARNING: finalization artifact could not be read: "
            f"{path} ({exc})",
            file=sys.stderr,
        )
        return False

    if not isinstance(payload, dict):
        return False
    artifact_at = payload.get(timestamp_field)
    if not isinstance(artifact_at, str):
        return False

    try:
        return datetime.fromisoformat(artifact_at) >= datetime.fromisoformat(
            aggregator_started_at
        )
    except (TypeError, ValueError):
        return False


def is_current_summary_artifact(
    path: Path,
    *,
    aggregator_started_at: str,
) -> bool:
    """Return whether ``final_summary.json`` was generated by this aggregator."""
    return _is_current_json_artifact(
        path,
        aggregator_started_at=aggregator_started_at,
        timestamp_field="generated_at",
    )


def read_current_finalization_reason(
    aggregator_dir: Path,
    *,
    aggregator_started_at: str,
) -> Optional[str]:
    """Return the current run's strongest structured finalization reason."""
    aggregator_dir = Path(aggregator_dir).resolve()
    if _is_current_json_artifact(
        aggregator_dir / FINALIZATION_ERROR_NAME,
        aggregator_started_at=aggregator_started_at,
        timestamp_field="completed_at",
    ):
        return "finalization_failed"
    if _is_current_json_artifact(
        aggregator_dir / FINALIZATION_WARNING_NAME,
        aggregator_started_at=aggregator_started_at,
        timestamp_field="completed_at",
    ):
        return "finalization_warning"
    return None


def _set_telemetry_fields(
    manifest: Dict[str, Any],
    *,
    telemetry_status: str,
    telemetry_reason: Optional[str],
    aggregator_exit_code: Optional[int],
) -> None:
    """Set one coherent telemetry-health fact on a run manifest."""
    manifest["telemetry_status"] = str(telemetry_status)

    if telemetry_reason is None:
        manifest.pop("telemetry_reason", None)
    else:
        manifest["telemetry_reason"] = str(telemetry_reason)

    if aggregator_exit_code is None:
        manifest.pop("aggregator_exit_code", None)
    else:
        manifest["aggregator_exit_code"] = int(aggregator_exit_code)


def write_code_manifest(
    session_root: Path,
    script_path: str,
) -> Optional[Path]:
    """Write static-analysis details for the launched script.

    Static analysis is useful metadata, not a reason to break a training run.
    If analysis fails, this helper writes a minimal failure manifest when
    possible and otherwise returns ``None``.
    """
    session_root = Path(session_root).resolve()
    session_root.mkdir(parents=True, exist_ok=True)

    manifest_path = session_root / "code_manifest.json"

    try:
        findings = analyze_script(str(Path(script_path).resolve()))
        manifest = build_code_manifest(findings)
        manifest["analysis_status"] = (
            "ok" if not findings.parse_errors else "partial"
        )
        write_json_atomic(manifest_path, manifest)
        return manifest_path
    except Exception as exc:
        fallback: Dict[str, Any] = {
            "schema_version": 1,
            "script_path": str(Path(script_path).resolve()),
            "generated_at": utc_now_iso(),
            "analysis_status": "failed",
            "parse_errors": [f"Static analysis failed: {exc}"],
        }
        try:
            write_json_atomic(manifest_path, fallback)
            return manifest_path
        except Exception:
            return None


def write_run_manifest(
    session_root: Path,
    session_id: str,
    script_path: str,
    profile: str,
    ui_mode: str,
    logs_dir: str,
    aggregator_host: str,
    aggregator_bind_host: str,
    aggregator_port: int,
    nnodes: int,
    node_rank: int,
    master_addr: str,
    master_port: int,
    nproc_per_node: int,
    history_enabled: bool,
    history_retention_s: float,
    finalize_timeout_sec: float,
    status: str,
    launch_cwd: str,
    run: Optional[Dict[str, Any]] = None,
    aggregator_dir: Optional[Path] = None,
    db_path: Optional[Path] = None,
    telemetry_status: Optional[str] = None,
    telemetry_reason: Optional[str] = None,
    aggregator_exit_code: Optional[int] = None,
    extra: Optional[Dict[str, Any]] = None,
) -> Path:
    """Write or overwrite a launcher run manifest under ``session_root``."""
    session_root = Path(session_root).resolve()
    session_root.mkdir(parents=True, exist_ok=True)

    manifest_path = session_root / "manifest.json"
    run_block: Dict[str, Any] = {
        "run_name": str(session_id),
        "session_id": str(session_id),
    }
    if run:
        run_block.update(run)

    manifest: Dict[str, Any] = {
        "schema_version": 1,
        "session_id": str(session_id),
        "run": run_block,
        "status": str(status),
        "created_at": utc_now_iso(),
        "lifecycle": {
            "training_started_at": None,
            "training_ended_at": None,
        },
        "host": {"hostname": socket.gethostname()},
        "launch": {
            "script_path": str(Path(script_path).resolve()),
            "profile": str(profile),
            "ui_mode": str(ui_mode),
            "logs_dir": str(Path(logs_dir).resolve()),
            "aggregator_host": str(aggregator_host),
            "aggregator_bind_host": str(aggregator_bind_host),
            "aggregator_port": int(aggregator_port),
            "nnodes": int(nnodes),
            "nproc_per_node": int(nproc_per_node),
            "node_rank": int(node_rank),
            "master_addr": str(master_addr),
            "master_port": int(master_port),
            "history_enabled": bool(history_enabled),
            "history_retention_s": float(history_retention_s),
            "finalize_timeout_sec": float(finalize_timeout_sec),
            "launch_cwd": str(Path(launch_cwd).resolve()),
        },
        "paths": {
            "session_root": str(session_root),
            "run_root": str(session_root),
            "aggregator_dir": (
                str(aggregator_dir.resolve()) if aggregator_dir else None
            ),
            "db_path": str(db_path.resolve()) if db_path else None,
        },
        "artifacts": {},
    }

    if extra:
        for key, value in extra.items():
            if key == "artifacts" and isinstance(value, dict):
                manifest.setdefault("artifacts", {}).update(value)
            else:
                manifest[key] = value

    if telemetry_status is not None:
        _set_telemetry_fields(
            manifest,
            telemetry_status=telemetry_status,
            telemetry_reason=telemetry_reason,
            aggregator_exit_code=aggregator_exit_code,
        )

    write_json_atomic(manifest_path, manifest)
    return manifest_path


def update_run_manifest(
    manifest_path: Path,
    *,
    status: Optional[str] = None,
    artifacts: Optional[Dict[str, Any]] = None,
    telemetry_status: Optional[str] = None,
    telemetry_reason: Optional[str] = None,
    aggregator_exit_code: Optional[int] = None,
    extra: Optional[Dict[str, Any]] = None,
) -> Path:
    """Update an existing run manifest in place using an atomic rewrite."""
    manifest_path = Path(manifest_path).resolve()
    manifest = load_json_or_warn(manifest_path)

    if status is not None:
        manifest["status"] = str(status)

    if status == "interrupted" and manifest.get("telemetry_status") in {
        "starting",
        "running",
    }:
        _set_telemetry_fields(
            manifest,
            telemetry_status="degraded",
            telemetry_reason=None,
            aggregator_exit_code=None,
        )

    manifest["updated_at"] = utc_now_iso()

    if artifacts:
        manifest.setdefault("artifacts", {}).update(artifacts)

    if extra:
        for key, value in extra.items():
            if key == "lifecycle" and isinstance(value, dict):
                manifest.setdefault("lifecycle", {}).update(value)
            else:
                manifest[key] = value

    if telemetry_status is not None:
        _set_telemetry_fields(
            manifest,
            telemetry_status=telemetry_status,
            telemetry_reason=telemetry_reason,
            aggregator_exit_code=aggregator_exit_code,
        )

    write_json_atomic(manifest_path, manifest)
    return manifest_path


def collect_existing_artifacts(
    db_path: Path,
    session_root: Optional[Path] = None,
    training_stdout_path: Optional[Path] = None,
    training_stderr_path: Optional[Path] = None,
    aggregator_stderr_path: Optional[Path] = None,
) -> Dict[str, str]:
    """Return only launcher artifacts that currently exist on disk."""
    candidates = {
        "db": db_path,
        "summary_card_json": Path(str(db_path) + "_summary_card.json"),
        "summary_card_txt": Path(str(db_path) + "_summary_card.txt"),
        "legacy_summary_card_json": Path(str(db_path) + ".summary_card.json"),
        "legacy_summary_card_txt": Path(str(db_path) + ".summary_card.txt"),
    }
    if session_root is not None:
        candidates["code_manifest"] = (
            Path(session_root).resolve() / "code_manifest.json"
        )
    if training_stdout_path is not None:
        candidates["training_stdout_log"] = Path(
            training_stdout_path
        ).resolve()
    if training_stderr_path is not None:
        candidates["training_stderr_log"] = Path(
            training_stderr_path
        ).resolve()
    if aggregator_stderr_path is not None:
        candidates["aggregator_stderr_log"] = Path(
            aggregator_stderr_path
        ).resolve()

    return {
        name: str(path) for name, path in candidates.items() if path.exists()
    }
