"""
Public TraceML module-level API.

This module provides the stable user-facing entrypoints exposed at
`import traceml`.

Design goals
------------
- Keep the public API simple and discoverable
- Preserve backward compatibility with existing decorator imports
"""

from typing import Any, Dict, Optional

from traceml.decorators import trace_model_instance, trace_step
from traceml.summary_client import final_summary as _final_summary


def final_summary(
    *,
    timeout_sec: float = 30.0,
    poll_interval_sec: float = 0.1,
    print_text: bool = False,
    rank0_only: bool = True,
) -> Optional[Dict[str, Any]]:
    """
    Return a finalized TraceML summary for the active session.

    Parameters
    ----------
    timeout_sec:
        Maximum time to wait for the aggregator to flush history, generate the
        summary, and publish the response artifact.
    poll_interval_sec:
        Poll interval used while waiting for the aggregator response.
    print_text:
        If True, print the final summary text artifact after it is generated.
    rank0_only:
        If True, return ``None`` on non-zero ranks. This avoids duplicate
        summary requests and duplicate logging in distributed training.

    Returns
    -------
    Optional[Dict[str, Any]]
        Parsed final summary JSON for the active session, or ``None`` when
        `rank0_only=True` and the current process is not rank 0.

    Notes
    -----
    - This API is intended to be called near the end of a training run.
    - The summary is generated by the aggregator process, not the training
      worker process. This preserves a single source of truth for multi-rank
      history and avoids cross-process summary drift.
    """
    return _final_summary(
        timeout_sec=timeout_sec,
        poll_interval_sec=poll_interval_sec,
        print_text=print_text,
        rank0_only=rank0_only,
    )


def start(*args: Any, **kwargs: Any) -> None:
    """
    Reserved for a future explicit TraceML lifecycle API.
    """
    raise NotImplementedError(
        "traceml.start() is not available yet in this version."
    )


def init(*args: Any, **kwargs: Any) -> None:
    """
    Reserved for a future explicit TraceML lifecycle API.
    """
    raise NotImplementedError(
        "traceml.init() is not available yet in this version."
    )


__all__ = [
    "trace_step",
    "trace_model_instance",
    "final_summary",
    "start",
    "init",
]
