"""
TraceML run comparison helpers.

This package compares two structured final summary JSON artifacts generated by
TraceML and produces both a machine-readable comparison JSON and a compact
human-readable text summary.
"""

from traceml.reporting.compare.command import compare_summaries
from traceml.reporting.compare.core import build_compare_payload
from traceml.reporting.compare.render import build_compare_text

__all__ = ["build_compare_payload", "build_compare_text", "compare_summaries"]
